<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <UserSecretsId>600d0803-2d0a-40b6-990d-02579da26a9f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="tests/**/*.cs" />
    <Content Remove="tests/**" />
    <Content Remove="reportsrepo/**" />
    <None Remove="reportsrepo/**" />
    <None Remove="tests/**" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.3" />
    <PackageReference Include="Microsoft.Identity.Web" Version="4.14.2" />
    <PackageReference Include="Microsoft.Identity.Web.UI" Version="4.14.2" />
  </ItemGroup>

</Project>
